site_name: Discoteca
theme:
  name: material
  custom_dir: overrides 
  extra_css:
    - stylesheets/extra.css
    - stylesheets/aesth.css
    - stylesheets/dock.css
    - stylesheets/homeicon.css
  extra_sass:
    - scss/aesth.scss
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
      # deep orange + lime
      primary: indigo
      accent: lime

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
        # color pairs:
        # deep purple + lime/orange/amber
        # deep orange + lime
        # black + orange/amber
        # cyan + amber/deep purple
        # blue grey + deep purple
      primary: indigo
      accent: lime
  font:
      # Good ones fonts: Roboto Flex, Open Sans
      # text: Open Sans
      # text: Roboto Flex
      # text: Font Awesome
      text: Google Sans
      code: Google Sans Mono
      # code: Fira Mono
  language: ru
  logo: assets/black-mesa.svg
  favicon: assets/shield-cat.svg
  features: 
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - toc.integrate
    - toc.follow
    - navigation.top
    # - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.expand
    # - navigation.indexes
    # - navigation.footer
  plugins: 
      - search
      - extra-sass
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
       smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


nav:
  - Home: _index.md
  - Themes: README.md 
  # - afk.GG: https://hootsdev.github.io/afk.GG/